### PR TITLE
Resiliency

### LINKED ISSUE #264: Improve Cluster Controller resiliency
Cluster Controller today cannot handle situations when some of the resources are deleted after the cluster was created. It seems that it cannot handle this neither when updating cluster nor when deleting them. We should improve the resilience:
- Delete should work in all cases
- Update should be ideally able to recreate the resources

### LINKED ISSUE #304: NPEs wile deleting Kafka cluster
```
2018-03-07 23:34:34 INFO  ClusterController:148 - ConfigMap my-cluster in namespace default was MODIFIED
2018-03-07 23:34:34 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
2018-03-07 23:34:34 INFO  ClusterController:148 - ConfigMap my-cluster in namespace default was DELETED
2018-03-07 23:34:34 INFO  AbstractClusterOperations:279 - Reconciliation: Kafka cluster my-cluster-kafka should be deleted
2018-03-07 23:34:34 INFO  AbstractClusterOperations:281 - Deleting Kafka cluster my-cluster in namespace default
2018-03-07 23:34:34 INFO  AbstractClusterOperations:150 - delete topic-controller cluster my-cluster-topic-controller in namespace default
2018-03-07 23:34:34 INFO  AbstractClusterOperations:279 - Reconciliation: Kafka cluster my-cluster-zookeeper should be deleted
2018-03-07 23:34:34 INFO  AbstractClusterOperations:281 - Deleting Kafka cluster my-cluster in namespace default
2018-03-07 23:34:34 INFO  AbstractOperations:99 - Deleting Deployment my-cluster-topic-controller in namespace default
2018-03-07 23:34:34 INFO  AbstractClusterOperations:150 - delete topic-controller cluster my-cluster-topic-controller in namespace default
2018-03-07 23:34:34 INFO  AbstractOperations:99 - Deleting Deployment my-cluster-topic-controller in namespace default
2018-03-07 23:34:34 INFO  AbstractOperations:101 - Deployment my-cluster-topic-controller in namespace default has been deleted
2018-03-07 23:34:34 INFO  AbstractClusterOperations:160 - topic-controller cluster my-cluster-topic-controller in namespace default: successful delete
2018-03-07 23:34:34 INFO  AbstractClusterOperations:150 - delete kafka cluster my-cluster-kafka in namespace default
2018-03-07 23:34:34 INFO  AbstractOperations:99 - Deleting ConfigMap my-cluster-kafka-metrics-config in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:101 - Deployment my-cluster-topic-controller in namespace default has been deleted
2018-03-07 23:34:35 INFO  AbstractClusterOperations:160 - topic-controller cluster my-cluster-topic-controller in namespace default: successful delete
2018-03-07 23:34:35 INFO  AbstractOperations:101 - ConfigMap my-cluster-kafka-metrics-config in namespace default has been deleted
2018-03-07 23:34:35 INFO  AbstractClusterOperations:150 - delete kafka cluster my-cluster-kafka in namespace default
2018-03-07 23:34:35 WARN  AbstractOperations:108 - ConfigMap my-cluster-kafka-metrics-config in namespace default doesn't exist, so cannot be deleted
2018-03-07 23:34:35 INFO  AbstractOperations:99 - Deleting StatefulSet my-cluster-kafka in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:99 - Deleting Service my-cluster-kafka-headless in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:101 - Service my-cluster-kafka-headless in namespace default has been deleted
2018-03-07 23:34:35 WARN  AbstractOperations:108 - Service my-cluster-kafka-headless in namespace default doesn't exist, so cannot be deleted
2018-03-07 23:34:35 INFO  AbstractOperations:99 - Deleting StatefulSet my-cluster-kafka in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:99 - Deleting Service my-cluster-kafka in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:99 - Deleting Service my-cluster-kafka in namespace default
2018-03-07 23:34:35 INFO  AbstractOperations:101 - Service my-cluster-kafka in namespace default has been deleted
2018-03-07 23:34:35 INFO  AbstractOperations:101 - Service my-cluster-kafka in namespace default has been deleted
2018-03-07 23:35:08 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace default...
2018-03-07 23:35:33 INFO  AbstractOperations:101 - StatefulSet my-cluster-kafka in namespace default has been deleted
2018-03-07 23:35:33 ERROR AbstractClusterOperations:163 - kafka cluster my-cluster-kafka in namespace default: failed to delete
2018-03-07 23:35:33 ERROR AbstractClusterOperations:289 - Failed to delete Kafka cluster my-cluster in namespace default
2018-03-07 23:35:33 INFO  AbstractOperations:101 - StatefulSet my-cluster-kafka in namespace default has been deleted
2018-03-07 23:35:33 ERROR AbstractClusterOperations:163 - kafka cluster my-cluster-kafka in namespace default: failed to delete
2018-03-07 23:35:33 ERROR AbstractClusterOperations:289 - Failed to delete Kafka cluster my-cluster in namespace default
2018-03-07 23:35:33 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
2018-03-07 23:35:33 INFO  AbstractClusterOperations:279 - Reconciliation: Kafka cluster my-cluster-zookeeper should be deleted
2018-03-07 23:35:33 INFO  AbstractClusterOperations:281 - Deleting Kafka cluster my-cluster in namespace default
2018-03-07 23:35:33 ERROR AbstractClusterOperations:152 - Error while getting required kafka cluster state for delete operation
java.lang.NullPointerException
	at io.strimzi.controller.cluster.resources.KafkaCluster.fromStatefulSet(KafkaCluster.java:158)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations$4.getCluster(KafkaClusterOperations.java:292)
	at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.execute(AbstractClusterOperations.java:149)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.deleteKafkaAndZookeeper(KafkaClusterOperations.java:390)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.delete(KafkaClusterOperations.java:384)
	at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$reconcile$5(AbstractClusterOperations.java:285)
	at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
2018-03-07 23:35:33 ERROR AbstractClusterOperations:289 - Failed to delete Kafka cluster my-cluster in namespace default
2018-03-07 23:35:33 INFO  AbstractClusterOperations:239 - Reconciling Kafka clusters ...
2018-03-07 23:35:33 INFO  AbstractClusterOperations:279 - Reconciliation: Kafka cluster my-cluster-zookeeper should be deleted
2018-03-07 23:35:33 INFO  AbstractClusterOperations:281 - Deleting Kafka cluster my-cluster in namespace default
2018-03-07 23:35:33 ERROR AbstractClusterOperations:152 - Error while getting required kafka cluster state for delete operation
java.lang.NullPointerException
	at io.strimzi.controller.cluster.resources.KafkaCluster.fromStatefulSet(KafkaCluster.java:158)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations$4.getCluster(KafkaClusterOperations.java:292)
	at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.execute(AbstractClusterOperations.java:149)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.deleteKafkaAndZookeeper(KafkaClusterOperations.java:390)
	at io.strimzi.controller.cluster.operations.cluster.KafkaClusterOperations.delete(KafkaClusterOperations.java:384)
	at io.strimzi.controller.cluster.operations.cluster.AbstractClusterOperations.lambda$reconcile$5(AbstractClusterOperations.java:285)
	at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
2018-03-07 23:35:33 ERROR AbstractClusterOperations:289 - Failed to delete Kafka cluster my-cluster in namespace default
2018-03-07 23:37:08 INFO  ClusterController:87 - Triggering periodic reconciliation for namespace default...
```

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Refactoring

### Description

This PR is identical to https://github.com/strimzi/strimzi/pull/329 but uses a branch name which doesn't cause problems with docker tags.

This PR fixes #264 and I believe it also fixes #304, #303, #264, #233 and #120. 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by tombentley** [comment]
@ppatierno tbh I was inclined to just squash them into a single commit.

**Comment by ppatierno** [comment]
@tombentley maybe most of them could make sense to have because they apply some "important" change. What I'm worried about are the commit for add just logging or debug more times due to CI failure I guess.

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/AbstractAssemblyOperator.java [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+
+    /**
+     * Reconcile assembly resources in the given namespace having the given selector.
+     * Reconciliation works by getting the assembly ConfigMaps in the given namespace with the given selector and
+     * comparing with the corresponding {@linkplain #getResources(String, Labels) resource}.
+     * <ul>
+     * <li>An assembly will be {@linkplain #createOrUpdate(Reconciliation, ConfigMap, Handler) created} for all ConfigMaps without same-named resources</li>
+     * <li>An assembly will be {@linkplain #delete(Reconciliation, Handler) deleted} for all resources without same-named ConfigMaps</li>
+     * </ul>
+     * @param namespace The namespace
```
Comment (ppatierno) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/AbstractAssemblyOperator.java]: It misses the `trigger` param in the Javadoc

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/Reconciliation.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+    private static final AtomicInteger IDS = new AtomicInteger();
+
+    private final String trigger;
+    private final String type;
+    private final String namespace;
+    private final String assemblyName;
+    private final int id;
+
+    public Reconciliation(String trigger, String type, String namespace, String assemblyName) {
```
Comment (ppatierno) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/Reconciliation.java]: Could it be more understandable having an enum for the trigger ? watcher, timer and so on ?

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 3]
```diff
@@ -0,0 +1,250 @@
...
+ * <p>Assembly operator for a "Kafka" assembly, which manages:</p>
+ * <ul>
+ *     <li>A ZooKeeper cluster StatefulSet and related Services</li>
+ *     <li>A Kafka cluster StatefulSet and related Services</li>
+ *     <li>Optionally, a TopicController Deployment</li>
+ * </ul>
+ */
+public class KafkaAssemblyOperator extends AbstractAssemblyOperator {
+    private static final Logger log = LoggerFactory.getLogger(KafkaAssemblyOperator.class.getName());
+    private static final String CLUSTER_TYPE_ZOOKEEPER = "zookeeper";
```
Comment (scholzj) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: `CLUSTER_TYPE_ZOOKEEPER` and `CLUSTER_TYPE_TOPIC_CONTROLLER` seem to be unused variables.

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 4]
```diff
@@ -0,0 +1,250 @@
...
+    static final String CLUSTER_TYPE_KAFKA = "kafka";
```
Comment (scholzj) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: You seem to use sometimes `CLUSTER_TYPE_KAFKA` and sometimes `KafkaCluster.TYPE`. Wouldn't it be better to use only `KafkaCluster.TYPE` (or set `CLUSTER_TYPE_KAFKA` to `KafkaCluster.TYPE`)?

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 5]
```diff
@@ -0,0 +1,250 @@
...
+                .compose(i -> deleteKafka(reconciliation))
+                .compose(i -> deleteZk(reconciliation))
+                .compose(ar -> f.complete(), f);
+    }
+
+    @Override
+    protected List<HasMetadata> getResources(String namespace, Labels selector) {
+        List<HasMetadata> result = new ArrayList<>();
+        result.addAll(kafkaSetOperations.list(namespace, Labels.forType(KafkaCluster.TYPE)));
+        result.addAll(zkSetOperations.list(namespace, Labels.forType(KafkaCluster.TYPE)));
```
Comment (scholzj) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: Do the Zookeeper resources really have as a type label `KafkaCluster.TYPE`? Shouldn't these be:
```
result.addAll(zkSetOperations.list(namespace, Labels.forType(ZookeeperCluster.TYPE)));
result.addAll(deploymentOperations.list(namespace, Labels.forType(TopicController.TYPE)));
result.addAll(serviceOperations.list(namespace, Labels.forType(KafkaCluster.TYPE)));
result.addAll(serviceOperations.list(namespace, Labels.forType(ZookeeperCluster.TYPE)));
```

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java [hunk 6]
```diff
@@ -0,0 +1,250 @@
...
+        result.addAll(deploymentOperations.list(namespace, Labels.forType(KafkaCluster.TYPE)));
+        result.addAll(serviceOperations.list(namespace, Labels.forType(KafkaCluster.TYPE)));
+        // TODO remove the cluster cm! result.addAll(configMapOperations.list(namespace, selector));
```
Comment (scholzj) [inline cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: I'm not sure what exactly was meant with this TODO. But should we also look for the metrics config maps here? (that could be easily a minor for another PR)

File: cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java (hunk 5 above)
Comment (tombentley) [reply cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: This is a really good point. Before I think we needed a label for the different clusters (kafka, zk), but I don't think we do now:

* For createOrUpdate() we identifiy resources by name, not by label.
* We still use labels when doing a periodic reconciliation (to identify what assemblies exist but which now lack a CM), but in this case we don't need to make a ZK/Kafka distinction: We just need to figure out the assembly name for which there's no matching CM. This works so long as the labels of all the resource share a common `type`, and each have their respective `cluster`: We use the `type` to find the resources and them map to the name of the cluster/assembly CM which owns them via the `cluster`.

So the CC doesn't really consume these zookeeper or topic controller labels itself, currently. I admit this has come about as a result of the refactoring, rather than being a conscious decision.

As I mentioned in a comment to @ppatierno ealier I think we should tidy this up. The `Labels.*type*()` methods should use something other than a `String` (probably an `enum`), and the `*cluster*()` methods should use an `enum`. This will make the API less confusing and more type-safe. We should also consider renaming the label `cluster` → `assembly`. I also think maybe `type` →`assembly.type` would also be more clear, though it's less concise. 

Thoughts?

Comment (scholzj) [reply cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: Wait ... what happens if I had a running Kafka cluster and now I delete the config map together with all Kafka resources (Kafka SS, Kafka services), but leave all Zookeeper resources? Will the reconciliation find them and delete them? With the current code it would simply ignore them, or?

Comment (tombentley) [reply cluster-controller/src/main/java/io/strimzi/controller/cluster/operator/assembly/KafkaAssemblyOperator.java]: I have now changed the code so that the reconciliation would find and delete the zk resources.

**Comment by tombentley** [comment]
@ppatierno @scholzj any further comments, questions, doubts?

**Comment by scholzj** [comment]
@tombentley Merge it :-)

**Comment by ppatierno** [comment]
@tombentley go for it !
