### PR TITLE
Logging exception and return when znode watching reports a failure

### LINKED ISSUE #238: Unhandled exception during updating value for zookeeper-healthcheck-delay in Config Map
Step to reproduce:

1. Clone and open Strimzi sources https://github.com/strimzi/strimzi
2. Up cluster
`$ oc clucter up`
3. Login as admin
`$ oc login -u system:admin`
4. Deploy Cluster Controller
`$ oc create -f resources/openshift/cluster-controller-with-template.yaml`
5. Deploy Topic Controller
`$ oc create -f resources/openshift/topic-controller-with-template.yaml`
6. Login to OpenShift https://127.0.0.1:8443
7. Create "Apache Kafka (Ephemeral storage)"
7.1 Click "Add to project"
7.2 Click "Select from project"
7.3 Select "Apache Kafka (Ephemeral storage)" and click "Next"
7.4 Use default configurations:
- Number of Zookeper cluster nodes: 1
- Number of Kafka cluster nodes: 3
- Zookeeper healthcheck initial delay: 15
- Zookeeper healthcheck timeout: 5
7.5 Click "Create" and wait for the message "Apache Kafka (Ephemeral storage) has been created"
7.6 Open page "Pods" and wait when all pods will have status "Running"
8. Create Strimzi Topic Controller
8.1 Click "Add to project"
8.2 Click "Select from project"
8.3 Select "Strimzi Topic Controller" and click "Next"
8.4 Use default configurations
8.5 Click "Create" and wait for the message "Success Strimzi Topic Controller has been created."
8.6 Open page "Pods" and wait when all pods will have status "Running"
9. Open page "Config Maps" and open your cluster config
10. Edit value for zookeeper-healthcheck-delay
10.1 Click "Actions"
10.2 Click "Edit YAML"
10.3 Set new value (30) for variable zookeeper-healthcheck-delay and save
11. Open page "Pods" and open logs for strimzi-topic-controller

Actual result:
Log has an unhandled exception:
```
[2018-02-21 15:48:18,807] WARN <ClientCnxn :1162> [.local:2181)] Session 0x161b8fedf870003 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
Feb 21, 2018 3:48:18 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for for path: /brokers/topics
at io.strimzi.controller.topic.TopicsWatcher.lambda$start$2(TopicsWatcher.java:67)
at io.strimzi.controller.topic.zk.ZkImpl.lambda$null$9(ZkImpl.java:347)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for for path: /brokers/topics
at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
at io.strimzi.controller.topic.zk.ZkImpl.mapResult(ZkImpl.java:135)
at io.strimzi.controller.topic.zk.ZkImpl.lambda$children$10(ZkImpl.java:342)
at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:601)
at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
```

Additional details:
Docker version: 18.02.0-ce
OpenShift server version: v3.7.1

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #238 just logging the failure reported by a znode child.
While using "ephemeral" storage as described by #238 doesn't make more sense even because Kafka brokers cannot deal with Zookeeper pod restart, using the "persistent" storage has another problem. The cluster works fine but the topic controller is not able to handle new topic CMs due "Session expired" errors on watched znode. I'm going to open another issue for that.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by ppatierno** [comment]
@tombentley @scholzj where do we want to write information about how it's not recommended to start a cluster with 1 Zookeeper node and "ephemeral" storage ? In the FAQ section or in the section where we describe the cluster ConfigMap ?

**Comment by tombentley** [comment]
@ppatierno In the FAQ section or in the section where we describe the cluster ConfigMap because people are less likely to read the FAQ

File: topic-controller/src/main/java/io/strimzi/controller/topic/TopicsWatcher.java [hunk 1]
```diff
@@ -106,7 +107,8 @@ void start(Zk zk) {
 
         }).children(TOPICS_ZNODE, childResult -> {
             if (childResult.failed()) {
-                throw new RuntimeException(childResult.cause());
+                LOGGER.error("Error on zone {} children", TOPICS_ZNODE, childResult.cause());
```
Comment (scholzj) [inline topic-controller/src/main/java/io/strimzi/controller/topic/TopicsWatcher.java]: This should probably say `znode` not `zone` (just a typo).

File: topic-controller/src/main/java/io/strimzi/controller/topic/TopicsWatcher.java [hunk 2]
```diff
@@ -64,7 +64,8 @@ void start(Zk zk) {
                 return;
             }
             if (childResult.failed()) {
-                throw new RuntimeException(childResult.cause());
+                LOGGER.error("Error on zone {} children", TOPICS_ZNODE, childResult.cause());
```
Comment (scholzj) [inline topic-controller/src/main/java/io/strimzi/controller/topic/TopicsWatcher.java]: This should probably say `znode` not `zone` (just a typo).

**Comment by ppatierno** [comment]
I tried to be more generic than specifying 1 Zk node + ephemeral storage. In general running with "ephemeral" storage could drive this kind of problems. Let me know if you prefer to add more or @tombentley can just update the branch ;)

File: documentation/adoc/cluster-controller.adoc [hunk 3]
```diff
@@ -135,6 +135,9 @@ data:
     }
 ----
 
+WARNING: If the cluster is deployed using the "ephemeral" storage, the Kafka brokers could have problems to deal with
+Zookeeper nodes restarts which could happen on configuration updates in the cluster ConfigMap.
+
```
Comment (tombentley) [inline documentation/adoc/cluster-controller.adoc]: I think we need to word this a little differently because the problem will definitely happen when:

* ZK is using ephemeral storage and
* ZK has only 1 node and
* The ZK pod is rolled, or otherwise get recreated

As it's currently worded is "could" have problems, but we're not be explicit about exactly which configurations will have these problems.

Comment (ppatierno) [reply documentation/adoc/cluster-controller.adoc]: @tombentley even if I have a 3 ZK nodes it could happen when I change a CM and a rolling update is started. In any case the 3 ZK pods lose their state and Kafka brokers cannot re-connect to the new ones.

Comment (scholzj) [reply documentation/adoc/cluster-controller.adoc]: @tombentley I don't think our rolling update is sophisticated enough to make sure that the same doesn't happen with 3 node ephemeral ZK cluster. We do not make sure that between the pod restarts the data are replicated. So we are 100% sure it happens with single node and we are XX% (==could) sure it happens with more nodes as well.
